---
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: false
  require_ansible_omnibus: true
  requirements_path: requirements.yml

driver:
  name: docker

platforms:
  - name: centos-6
    driver_config:
      image: dynatrace/centos-testing:6
  - name: debian-7.8
    driver_config:
      image: dynatrace/debian-testing:7.8
  - name: ubuntu-12.04
    driver_config:
      image: dynatrace/ubuntu-testing:12.04

suites:
  - name: default
