---
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/d185d6849ac275e544614ab01bbb55b0cabbef8c/ansible_install.sh
  require_chef_omnibus: 13.0.118

driver:
  name: docker
  # In case of error "Message: You must first install the Docker CLI tool" try uncommenting following line
  use_sudo: false

platforms:
  - name: centos-6
    driver_config:
      provision_command:
        - yum update -y
        - yum install -y net-tools tar
  - name: debian-7.8
    driver_config:
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar
  - name: ubuntu-12.04
    driver_config:
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar

suites:
  - name: default
