---
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: false
  require_ansible_omnibus: true
  requirements_path: requirements.yml

driver:
  name: docker

platforms:
  - name: centos-6
    driver_config:
      provision_command:
        - yum update -y
        - yum install -y net-tools tar
  - name: debian-7.8
    driver_config:
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar
  - name: ubuntu-12.04
    driver_config:
      provision_command:
        - apt-get update
        - apt-get install -y net-tools tar

suites:
  - name: default
