---
- name: Check if a Dynatrace Server installer is provided locally
  local_action: stat path="{{ playbook_dir }}/roles/{{ dynatrace_server_role_name }}/files/linux/{{ dynatrace_server_linux_installer_file_name }}"
  register: dynatrace_server_installer_provided

- name: Fail if the Dynatrace Server installer is not provided locally
  fail: msg="The Dynatrace Server installer is not provided at {{ playbook_dir }}/roles/{{ dynatrace_server_role_name }}/files/linux/{{ dynatrace_server_linux_installer_file_name }}."
  when: not dynatrace_server_installer_provided.stat.exists

- name: Check if a Dynatrace fixpack is provided locally
  local_action: stat path="{{ playbook_dir }}/roles/{{ dynatrace_server_role_name }}/files/{{ dynatrace_server_fixpack_file_name }}"
  register: dynatrace_fixpack_provided
- debug: msg="Dynatrace fixpack provided:{{ dynatrace_fixpack_provided.stat.exists }}"

- name: Check if a Dynatrace license is provided locally
  local_action: stat path="{{ playbook_dir }}/roles/{{ dynatrace_server_role_name }}/files/{{ dynatrace_server_license_file_name }}"
  register: dynatrace_license_provided
- debug: msg="Dynatrace license provided:{{ dynatrace_license_provided.stat.exists }}"

- include: linux/install-dependencies-apt.yml
  when: dynatrace_server_installer_provided.stat.exists and ansible_pkg_mgr == "apt"
- include: linux/install-dependencies-yum.yml
  when: dynatrace_server_installer_provided.stat.exists and ansible_pkg_mgr == "yum"

- include: linux/install-dynatrace-user.yml
  when: dynatrace_server_installer_provided.stat.exists

- include: linux/install-dynatrace-server.yml
  when: dynatrace_server_installer_provided.stat.exists

- include: linux/install-dynatrace-license.yml
  when: dynatrace_license_provided.stat.exists

- include: linux/install-dynatrace-fixpack.yml
  when: dynatrace_fixpack_provided.stat.exists

- include: linux/remove-dependencies-apt.yml
  when: dynatrace_server_installer_provided.stat.exists and ansible_pkg_mgr == "apt"
- include: linux/remove-dependencies-yum.yml
  when: dynatrace_server_installer_provided.stat.exists and ansible_pkg_mgr == "yum"
