---
- name: Check if 'curl' is on the PATH
  shell: which curl
  register: which_curl_cmd
  ignore_errors: yes
  become: yes

- name: Install package 'curl'
  yum:
    pkg: curl
    state: present
  register: curl_install
  when: which_curl_cmd.rc != 0
  become: yes

- name: Check if 'java' is on the PATH
  shell: which java
  register: which_java_cmd
  ignore_errors: yes
  become: yes

- name: Install package 'java-1.7.0-openjdk'
  yum:
    pkg: java-1.7.0-openjdk
    state: present
  register: java_install
  when: which_java_cmd.rc != 0
  become: yes
